<?php
declare(strict_types=1);
require_once __DIR__.'/app.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$token=trim((string)($_GET['t']??''));
if(!$id||!verify_gallery_token($id,$token)){http_response_code(404);exit('Anúncio não encontrado.');}
try{$rows=supabase_request('GET','/rest/v1/imoveis?select=*&id=eq.'.$id.'&limit=1');$imovel=$rows[0]??null;$perfil=profile_data();}catch(Throwable){http_response_code(500);exit('Não foi possível carregar o anúncio.');}
if(!$imovel){http_response_code(404);exit('Anúncio não encontrado.');}
$fotos=is_array($imovel['fotos']??null)?$imovel['fotos']:[];$fotos=array_values(array_filter($fotos,fn($f)=>is_array($f)&&!empty($f['url'])));
$showLocation=isset($_GET['localizacao'])&&$_GET['localizacao']==='1'&&!empty($imovel['latitude'])&&!empty($imovel['longitude']);
$features=[];foreach([[(int)($imovel['capacidade']??0),'pessoas'],[(int)($imovel['dormitorios']??0),'dormitórios'],[(int)($imovel['suites']??0),'suítes']] as $f){if($f[0]>0)$features[]=$f[0].' '.$f[1];}foreach([['piscina','Piscina'],['churrasqueira','Churrasqueira'],['ar_condicionado','Ar-condicionado']] as $f){if(!empty($imovel[$f[0]]))$features[]=$f[1];}
$shareBase=gallery_url($id);$urlNo=$shareBase.'&anuncio=1&localizacao=0';$urlYes=$shareBase.'&anuncio=1&localizacao=1';
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?=e($imovel['nome'])?> · <?=e($imovel['codigo'])?></title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
:root{--bg:#f6f5f2;--surface:#fff;--ink:#17212b;--muted:#6d7782;--line:#dedfdc;--accent:#c91824}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{width:min(1080px,calc(100% - 28px));margin:auto;padding:24px 0 50px}.top{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:22px}.brand{font-size:12px;font-weight:850;letter-spacing:.12em;text-transform:uppercase}.agent{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:12px}.agent img,.avatar{width:38px;height:38px;border-radius:50%;object-fit:cover;background:#e9ebed;border:1px solid var(--line)}.hero{display:grid;grid-template-columns:1.6fr .75fr;gap:18px}.hero-img{height:500px;border-radius:20px;overflow:hidden;background:#111}.hero-img img{width:100%;height:100%;object-fit:cover}.info{background:var(--surface);border:1px solid var(--line);border-radius:20px;padding:25px}.eyebrow{font-size:10px;font-weight:850;letter-spacing:.16em;color:var(--muted)}h1{font-size:clamp(32px,5vw,52px);letter-spacing:-.055em;line-height:.98;margin:8px 0 10px}.location{color:var(--muted);font-size:14px}.price{font-size:24px;font-weight:850;margin:25px 0 17px}.features{display:flex;flex-wrap:wrap;gap:7px}.feature{border:1px solid var(--line);border-radius:999px;padding:7px 10px;font-size:11px}.desc{margin-top:22px;color:#56616c;line-height:1.7;font-size:14px;white-space:pre-line}.photos{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:18px}.photos img{width:100%;height:210px;object-fit:cover;border-radius:12px}.section{margin-top:28px}.section h2{font-size:20px;margin:0 0 10px}.map{height:340px;border-radius:18px;overflow:hidden;border:1px solid var(--line)}.map-note{margin-top:9px;color:var(--muted);font-size:11px}.contact{margin-top:28px;background:var(--ink);color:#fff;border-radius:18px;padding:22px;display:flex;justify-content:space-between;align-items:center;gap:18px}.contact p{margin:5px 0 0;color:#c7ccd1;font-size:13px}.contact a{display:inline-flex;padding:11px 15px;border-radius:9px;background:#fff;color:var(--ink);font-weight:800;text-decoration:none}.tools{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:14px}.tools a{padding:8px 10px;border:1px solid var(--line);border-radius:9px;color:var(--ink);background:var(--surface);font-size:11px;font-weight:750;text-decoration:none}.foot{margin-top:30px;text-align:center;color:var(--muted);font-size:11px}@media(max-width:780px){.hero{grid-template-columns:1fr}.hero-img{height:350px}.photos{grid-template-columns:repeat(2,1fr)}.photos img{height:170px}.contact{display:block}.contact a{margin-top:13px}}
</style></head><body><main class="wrap"><header class="top"><div class="brand">Central Imóveis</div><div class="agent"><?php if(!empty($perfil['foto_url'])):?><img src="<?=e($perfil['foto_url'])?>" alt="<?=e($perfil['nome']??'Corretor')?>"><?php else:?><div class="avatar"></div><?php endif;?><span><?=e($perfil['nome']??'Atendimento imobiliário')?><br><?=!empty($perfil['creci'])?'CRECI '.e($perfil['creci']):'Litoral Norte · SP'?></span></div></header>
<div class="tools"><a href="<?=$urlNo?>">Sem localização</a><?php if(!empty($imovel['latitude'])&&!empty($imovel['longitude'])):?><a href="<?=$urlYes?>">Mostrar localização aproximada</a><?php endif;?></div>
<section class="hero"><div class="hero-img"><?php if($fotos):?><img src="<?=e($fotos[0]['url'])?>" alt="<?=e($imovel['nome'])?>"><?php endif;?></div><aside class="info"><div class="eyebrow"><?=e($imovel['codigo'])?></div><h1><?=e($imovel['nome'])?></h1><div class="location"><?=e($imovel['bairro']??'')?><?php if(!empty($imovel['cidade'])):?> · <?=e($imovel['cidade'])?>/<?=e($imovel['uf']??'SP')?><?php endif;?></div><?php if((float)($imovel['diaria']??0)>0):?><div class="price">R$ <?=number_format((float)$imovel['diaria'],2,',','.')?> <small style="font-size:12px;font-weight:500;color:var(--muted)">/ diária base</small></div><?php endif;?><div class="features"><?php foreach($features as $f):?><span class="feature"><?=e($f)?></span><?php endforeach;?></div><div class="desc"><?=e($imovel['descricao']??'')?></div></aside></section>
<?php if(count($fotos)>1):?><section class="section"><h2>Fotos</h2><div class="photos"><?php foreach(array_slice($fotos,1) as $foto):?><img src="<?=e($foto['url'])?>" alt="Foto do imóvel" loading="lazy"><?php endforeach;?></div></section><?php endif;?>
<?php if($showLocation):?><section class="section"><h2>Localização aproximada</h2><div id="map" class="map"></div><div class="map-note">A área indicada é aproximada e não revela a localização exata do imóvel.</div></section><?php endif;?>
<section class="contact"><div><strong>Gostou deste imóvel?</strong><p><?=e($perfil['nome']??'Entre em contato')?><?php if(!empty($perfil['telefone'])):?> · <?=e($perfil['telefone'])?><?php endif;?></p></div><?php if(!empty($perfil['telefone'])):?><a href="https://wa.me/55<?=preg_replace('/\D+/','',$perfil['telefone'])?>" target="_blank" rel="noopener">Falar no WhatsApp</a><?php endif;?></section><div class="foot">Informações sujeitas a confirmação. Material preparado para atendimento de locação.</div></main>
<?php if($showLocation):?><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const lat=<?=json_encode((float)$imovel['latitude'])?>,lng=<?=json_encode((float)$imovel['longitude'])?>;const map=L.map('map',{scrollWheelZoom:false}).setView([lat,lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);L.circle([lat,lng],{radius:300,color:'#3b82f6',fillColor:'#60a5fa',fillOpacity:.22,weight:2}).addTo(map);</script><?php endif;?></body></html>
