<?php require_once __DIR__ . '/app.php'; require_login(); ?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Novo imóvel · Central Imóveis</title><link rel="stylesheet" href="css/style.css"></head><body>
<main class="container form-page">
<header class="inner-head"><div><span class="eyebrow">CENTRAL IMÓVEIS · NOVO</span><h1>Novo imóvel</h1><p class="subtitulo">Cadastre o imóvel e deixe o endereço pronto para mapa, atendimento e organização.</p></div><?php render_nav("imoveis"); ?></header>
<?php if($error=flash('error')): ?><div class="alerta erro"><?=e($error)?></div><?php endif; ?>
<form id="cadastroForm" action="salvar.php" method="POST" class="formulario">
<?=csrf_field()?>
<section class="form-card"><div class="form-card-title"><span>01</span><div><strong>Identificação</strong><small>Como o imóvel aparece na Central.</small></div></div>
<div class="grid"><label>Código *<input name="codigo" required maxlength="50" placeholder="Ex.: REF-001"></label><label>Nome do imóvel *<input name="nome" required maxlength="150" placeholder="Casa 3 suítes 200m do mar"></label></div>
<label>Proprietário<select name="proprietario_id"><option value="">Selecionar depois</option><?php $owners=supabase_request('GET','/rest/v1/proprietarios?select=id,nome,tipo&order=nome.asc'); foreach((array)$owners as $owner): ?><option value="<?= (int)$owner['id'] ?>"><?= e($owner['nome']) ?><?= ($owner['tipo']??'pf')==='pj'?' · PJ':'' ?></option><?php endforeach; ?></select></label><input type="hidden" name="proprietario" value=""></section>
<section class="form-card"><div class="form-card-title"><span>02</span><div><strong>Endereço inteligente</strong><small>Digite o CEP e o sistema completa os dados automaticamente.</small></div></div>
<div class="cep-row"><label>CEP<input id="cep" name="cep" inputmode="numeric" autocomplete="postal-code" maxlength="9" placeholder="00000-000"><small id="cepStatus" class="field-status">Consulta automática pelo ViaCEP.</small></label><button id="cepBtn" class="botao secundario cep-btn" type="button">Buscar CEP</button></div>
<div class="grid"><label>Rua / logradouro<input id="endereco" name="endereco" maxlength="250" autocomplete="street-address" placeholder="Nome da rua ou avenida"></label><label>Número<input id="numero" name="numero" maxlength="20" inputmode="numeric" placeholder="Número do imóvel"></label></div>
<div class="grid"><label>Complemento<input id="complemento" name="complemento" maxlength="120" placeholder="Apartamento, bloco, casa ou complemento"></label><label>Bairro<input id="bairro" name="bairro" maxlength="100" autocomplete="address-level3" placeholder="Nome do bairro"></label></div>
<div class="grid"><label>Cidade<input id="cidade" name="cidade" maxlength="100" autocomplete="address-level2" value="São Sebastião" placeholder="Cidade"></label><label>UF<input id="uf" name="uf" maxlength="2" value="SP" autocomplete="address-level1" placeholder="UF"></label></div>
<div class="location-note">Depois de salvar, o endereço também é usado para tentar posicionar o imóvel no mapa. A localização pode ser ajustada pelas coordenadas.</div>
<div class="grid"><label>Latitude<input type="number" name="latitude" step="any" placeholder="Preenchida pelo mapa"></label><label>Longitude<input type="number" name="longitude" step="any" placeholder="Preenchida pelo mapa"></label></div></section>
<section class="form-card"><div class="form-card-title"><span>03</span><div><strong>Características</strong><small>Informações rápidas para consulta e apresentação.</small></div></div>
<div class="grid quatro"><label>Capacidade<input type="number" name="capacidade" min="0" value="0" placeholder="Quantidade de pessoas"></label><label>Dormitórios<input type="number" name="dormitorios" min="0" value="0" placeholder="Quantidade de dormitórios"></label><label>Suítes<input type="number" name="suites" min="0" value="0" placeholder="Quantidade de suítes"></label><label>Distância da praia (m)<input type="number" name="distancia_praia" min="0" value="0" placeholder="Distância em metros"></label></div>
<div class="checks"><label><input type="checkbox" name="suite_terrea"> Suíte térrea</label><label><input type="checkbox" name="piscina"> Piscina</label><label><input type="checkbox" name="churrasqueira"> Churrasqueira</label><label><input type="checkbox" name="ar_condicionado"> Ar-condicionado</label></div>
<div class="other-field"><label>Outros <span class="field-hint">+</span><input name="observacao" maxlength="500" placeholder="Ex.: varanda, sauna, elevador, vista aberta..."></label></div></section>
<section class="form-card"><div class="form-card-title"><span>04</span><div><strong>Comercial</strong><small>Base de preço e descrição do imóvel.</small></div></div>
<label>Diária base<input type="number" name="diaria" min="0" step="0.01" value="0" placeholder="Valor da diária"></label><label>Descrição<textarea name="descricao" rows="7" placeholder="Descreva os principais diferenciais e condições do imóvel"></textarea></label><label class="check-unico"><input type="checkbox" name="ativo" checked> Imóvel ativo</label></section>
<div class="form-bottom"><a class="botao secundario" href="index.php">Cancelar</a><button id="salvarBtn" class="botao" type="submit">Cadastrar imóvel</button></div>
</form><?php render_footer(); ?></main>
<script>
const cep=document.getElementById('cep'),status=document.getElementById('cepStatus'),btn=document.getElementById('cepBtn');function limpaCepMascara(v){return v.replace(/\D/g,'').slice(0,8)}function mascaraCep(){const v=limpaCepMascara(cep.value);cep.value=v.length>5?v.slice(0,5)+'-'+v.slice(5):v}async function buscarCep(){const value=limpaCepMascara(cep.value);if(value.length!==8){status.textContent='Digite um CEP com 8 números.';status.className='field-status error';return}btn.disabled=true;status.textContent='Consultando endereço…';status.className='field-status';try{const r=await fetch('https://viacep.com.br/ws/'+value+'/json/');const d=await r.json();if(d.erro)throw new Error('CEP não encontrado.');document.getElementById('endereco').value=d.logradouro||'';document.getElementById('bairro').value=d.bairro||'';document.getElementById('cidade').value=d.localidade||'';document.getElementById('uf').value=d.uf||'';status.textContent='Endereço encontrado. Confira o número.';status.className='field-status ok';document.getElementById('numero').focus()}catch(e){status.textContent=e.message||'Não foi possível consultar o CEP.';status.className='field-status error'}finally{btn.disabled=false}}cep.addEventListener('input',mascaraCep);cep.addEventListener('blur',()=>{if(limpaCepMascara(cep.value).length===8)buscarCep()});btn.addEventListener('click',buscarCep);document.getElementById('cadastroForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,b=document.getElementById('salvarBtn');b.disabled=true;b.textContent='Cadastrando…';const fd=new FormData(form);fd.append('ajax','1');try{const r=await fetch('salvar.php',{method:'POST',body:fd,credentials:'same-origin'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Não foi possível cadastrar.');location.href=j.redirect}catch(err){alert(err.message);b.disabled=false;b.textContent='Cadastrar imóvel'}});
</script></body></html>