<?php
require_once __DIR__.'/app.php'; require_login();
$id=filter_input(INPUT_GET,'imovel',FILTER_VALIDATE_INT); if(!$id){flash('error','Imóvel inválido.');redirect('index.php');}
$rows=supabase_request('GET','/rest/v1/imoveis?select=id,codigo,nome&id=eq.'.$id.'&limit=1');$imovel=$rows[0]??null;if(!$imovel){flash('error','Imóvel não encontrado.');redirect('index.php');}
$month=$_GET['mes']??date('Y-m'); if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');$start=$month.'-01';$dt=new DateTimeImmutable($start);$end=$dt->modify('last day of this month');$entries=supabase_request('GET','/rest/v1/disponibilidade?select=*&imovel_id=eq.'.$id.'&and=(data_inicio.lte.'.$end->format('Y-m-d').',data_fim.gte.'.$start.')&order=data_inicio.asc');$entries=is_array($entries)?$entries:[];
$byDay=[];foreach($entries as $e){$a=new DateTimeImmutable($e['data_inicio']);$b=new DateTimeImmutable($e['data_fim']);for($d=$a;$d<=$b;$d=$d->modify('+1 day')){$k=$d->format('Y-m-d');if($d->format('Y-m')===$month)$byDay[$k][]=$e;}}
$firstWeek=(int)$dt->format('N');$days=(int)$end->format('j');$prev=$dt->modify('-1 month')->format('Y-m');$next=$dt->modify('+1 month')->format('Y-m');
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Disponibilidade · <?=e($imovel['nome'])?></title><link rel="stylesheet" href="css/style.css"></head><body><main class="container">
<a class="voltar" href="index.php">← Voltar</a><?php render_nav("imoveis"); ?>
<header class="page-head"><div><span class="eyebrow">AGENDA PRIVADA</span><h1><?=e($imovel['nome'])?></h1><p class="subtitulo"><?=e($imovel['codigo'])?> · Disponibilidade e valor — somente você vê.</p></div></header>
<?php if($m=flash('success')):?><div class="alerta sucesso"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="alerta erro"><?=e($m)?></div><?php endif;?>
<section class="calendar-layout"><div class="painel"><div class="calendar-head"><a class="botao secundario" href="?imovel=<?=$id?>&mes=<?=$prev?>">←</a><h2><?=e($dt->format('F Y'))?></h2><a class="botao secundario" href="?imovel=<?=$id?>&mes=<?=$next?>">→</a></div><div class="calendar-grid calendar-week"><strong>Seg</strong><strong>Ter</strong><strong>Qua</strong><strong>Qui</strong><strong>Sex</strong><strong>Sáb</strong><strong>Dom</strong></div><div class="calendar-grid"><?php for($i=1;$i<$firstWeek;$i++):?><div class="day empty-day"></div><?php endfor;for($day=1;$day<=$days;$day++):$key=$dt->setDate((int)$dt->format('Y'),(int)$dt->format('m'),$day)->format('Y-m-d');$items=$byDay[$key]??[];$item=$items[0]??null;?><div class="day <?= $item?'day-'.$item['status']:''?>"><b><?=$day?></b><?php if($item):?><small><?=e(ucfirst($item['status']))?></small><strong>R$ <?=number_format((float)$item['valor'],2,',','.')?></strong><?php else:?><small>Disponível</small><?php endif;?></div><?php endfor;?></div></div>
<section class="painel"><h2>Adicionar período</h2><form action="salvar_disponibilidade.php" method="POST" class="formulario"><?=csrf_field()?><input type="hidden" name="imovel_id" value="<?=$id?>"><input type="hidden" name="mes" value="<?=e($month)?>"><div class="grid"><label>Início<input type="date" name="data_inicio" required></label><label>Fim<input type="date" name="data_fim" required></label></div><div class="grid"><label>Valor do período<input type="number" name="valor" min="0" step="0.01" required></label><label>Status<select name="status"><option value="disponivel">Disponível</option><option value="reservado">Reservado</option><option value="bloqueado">Bloqueado</option></select></label></div><label>Observação<textarea name="observacao" rows="3" placeholder="Ex.: Réveillon, manutenção, cliente X..."></textarea></label><button class="botao" type="submit">Adicionar período</button></form></section></section>
<section class="painel"><h2>Períodos cadastrados</h2><?php if(!$entries):?><p class="muted">Nenhum período cadastrado ainda.</p><?php else:?><div class="availability-list"><?php foreach($entries as $e):?><div class="availability-row"><div><strong><?=date('d/m/Y',strtotime($e['data_inicio']))?> → <?=date('d/m/Y',strtotime($e['data_fim']))?></strong><span><?=e(ucfirst($e['status']))?> · R$ <?=number_format((float)$e['valor'],2,',','.')?></span><?php if(!empty($e['observacao'])):?><small><?=e($e['observacao'])?></small><?php endif;?></div><form action="excluir_disponibilidade.php" method="POST" onsubmit="return confirm('Excluir este período?')"><?=csrf_field()?><input type="hidden" name="id" value="<?=$e['id']?>"><input type="hidden" name="imovel_id" value="<?=$id?>"><input type="hidden" name="mes" value="<?=e($month)?>"><button class="botao perigo" type="submit">Excluir</button></form></div><?php endforeach;?></div><?php endif;?></section>
<?php render_footer(); ?></main></body></html>