<?php
require_once __DIR__ . '/app.php'; require_login();
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); if(!$id){flash('error','Imóvel inválido.');redirect('index.php');}
$rows=supabase_request('GET','/rest/v1/imoveis?select=*&id=eq.'.$id.'&limit=1');$imovel=$rows[0]??null;if(!$imovel){flash('error','Imóvel não encontrado.');redirect('index.php');}
$fotos=is_array($imovel['fotos']??null)?$imovel['fotos']:[];$capa=null;$biblioteca=[];foreach($fotos as $foto){if(($foto['tipo']??'')==='capa'&&!$capa)$capa=$foto;else $biblioteca[]=$foto;}
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Editar <?=e($imovel['nome'])?></title><link rel="stylesheet" href="css/style.css"></head><body>
<main class="container pequeno"><a class="voltar" href="index.php">← Voltar</a><?php render_nav("imoveis"); ?><h1>Editar imóvel</h1><p class="subtitulo"><strong><?=e($imovel['codigo'])?></strong> · <?=e($imovel['nome'])?></p>
<?php if($error=flash('error')): ?><div class="alerta erro"><?=e($error)?></div><?php endif; ?><?php if($success=flash('success')): ?><div class="alerta sucesso"><?=e($success)?></div><?php endif; ?>
<form action="atualizar.php" method="POST" class="formulario"><?=csrf_field()?><input type="hidden" name="id" value="<?= (int)$id ?>">
<div class="grid"><label>Código *<input name="codigo" required maxlength="50" value="<?=e($imovel['codigo'])?>"></label><label>Nome *<input name="nome" required maxlength="150" value="<?=e($imovel['nome'])?>"></label></div>
<div class="grid"><label>Bairro<input name="bairro" maxlength="100" value="<?=e($imovel['bairro'])?>"></label><label>Endereço<input name="endereco" maxlength="250" value="<?=e($imovel['endereco'])?>"></label></div>
<div class="grid"><label>Proprietário<input name="proprietario" maxlength="150" value="<?=e($imovel['proprietario'])?>"></label><div class="location-note">Endereço, latitude e longitude alimentam o mapa.</div></div>
<div class="grid"><label>Latitude<input type="number" name="latitude" step="any" value="<?=e($imovel['latitude']??'')?>"></label><label>Longitude<input type="number" name="longitude" step="any" value="<?=e($imovel['longitude']??'')?>"></label></div><div class="grid quatro"><label>Capacidade<input type="number" name="capacidade" min="0" value="<?= (int)$imovel['capacidade']?>"></label><label>Dormitórios<input type="number" name="dormitorios" min="0" value="<?= (int)$imovel['dormitorios']?>"></label><label>Suítes<input type="number" name="suites" min="0" value="<?= (int)$imovel['suites']?>"></label><label>Distância da praia (m)<input type="number" name="distancia_praia" min="0" value="<?= (int)$imovel['distancia_praia']?>"></label></div>
<div class="checks"><label><input type="checkbox" name="suite_terrea" <?=!empty($imovel['suite_terrea'])?'checked':''?>> Suíte térrea</label><label><input type="checkbox" name="piscina" <?=!empty($imovel['piscina'])?'checked':''?>> Piscina</label><label><input type="checkbox" name="churrasqueira" <?=!empty($imovel['churrasqueira'])?'checked':''?>> Churrasqueira</label><label><input type="checkbox" name="ar_condicionado" <?=!empty($imovel['ar_condicionado'])?'checked':''?>> Ar-condicionado</label></div>
<label>Diária base<input type="number" name="diaria" min="0" step="0.01" value="<?=e($imovel['diaria'])?>"></label><label>Descrição<textarea name="descricao" rows="7"><?=e($imovel['descricao'])?></textarea></label><label class="check-unico"><input type="checkbox" name="ativo" <?=!empty($imovel['ativo'])?'checked':''?>> Imóvel ativo</label>
<div class="acoes-form"><a class="botao secundario" href="calendario.php?imovel=<?=(int)$id?>">📅 Disponibilidade</a><a class="botao secundario" href="mapa.php">🗺️ Mapa</a><a class="botao secundario" href="index.php">Cancelar</a><button class="botao" type="submit">Salvar dados</button></div>
</form>
<section class="fotos-editor upload-manager"><div class="secao-titulo"><div><span class="eyebrow">01 · IDENTIFICAÇÃO</span><h2>Foto de capa</h2><p>Uma imagem principal. Ela aparece no cartão do imóvel.</p></div></div><div class="upload-row"><label class="upload-box"><span class="upload-icone">▣</span><span><strong>Escolher capa</strong><small>JPG, PNG, WEBP ou GIF</small></span><input id="capaInput" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><div id="capaPreview" class="mini-preview"><?php if($capa): ?><img src="<?=e($capa['url'])?>" alt="Capa"><small>Capa atual</small><?php else: ?><small>Nenhuma capa definida.</small><?php endif;?></div></div></section>
<section class="fotos-editor upload-manager"><div class="secao-titulo"><div><span class="eyebrow">02 · ACERVO</span><h2>Biblioteca de fotos</h2><p>Selecione quantas fotos quiser. O sistema envia uma por vez para o Cloudinary.</p></div></div><label class="upload-box"><span class="upload-icone">＋</span><span><strong>Adicionar fotos à biblioteca</strong><small>Quantidade livre · envio automático em fila</small></span><input id="bibliotecaInput" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><div id="uploadStatus" class="upload-status">Nenhum upload em andamento.</div><div id="fila" class="fila"></div><div class="biblioteca-count"><strong><?=count($biblioteca)?></strong> fotos na biblioteca</div></section>
<section class="fotos-editor"><div class="secao-titulo"><div><span class="eyebrow">GALERIA</span><h2>Fotos atuais</h2></div><div class="acoes-form"><a class="botao" target="_blank" rel="noopener" href="<?=e(gallery_url($id))?>">📸 Abrir galeria</a><a class="botao secundario" href="download_fotos.php?id=<?=(int)$id?>">⬇️ Baixar tudo (.ZIP)</a><a class="botao secundario" target="_blank" rel="noopener" href="<?=e(gallery_url($id))?>&modo=pdf">📄 Versão para PDF</a></div></div><div class="galeria-editavel"><?php foreach($fotos as $foto): ?><?php $publicId=(string)($foto['public_id']??''); ?><div class="foto-editavel" data-public-id="<?=e($publicId)?>"><div class="foto-thumb"><img src="<?=e($foto['url']??'')?>" alt="Foto"></div><div class="foto-meta"><small><?=($foto['tipo']??'biblioteca')==='capa'?'CAPA':'BIBLIOTECA'?></small><button class="excluir-foto" type="button" onclick="excluirFoto(this,<?=json_encode($publicId)?>)">Excluir</button></div></div><?php endforeach;?></div></section>
<?php render_footer(); ?>
</main>
<script>
const id=<?= (int)$id ?>,csrf=<?=json_encode(csrf_token())?>;const capaInput=document.getElementById('capaInput'),bibliotecaInput=document.getElementById('bibliotecaInput'),statusEl=document.getElementById('uploadStatus'),fila=document.getElementById('fila');
async function enviar(file,tipo,item){const fd=new FormData();fd.append('id',id);fd.append('csrf',csrf);fd.append('tipo',tipo);fd.append('foto',file);const r=await fetch('upload_foto.php',{method:'POST',body:fd,credentials:'same-origin'});const text=await r.text();let j;try{j=JSON.parse(text)}catch(_){throw new Error('O servidor respondeu sem JSON. Verifique o log do Render.');}if(!r.ok||!j.ok)throw new Error(j.error||'Falha no upload');if(item)item.classList.add('ok');return j;}
capaInput.addEventListener('change',async()=>{const file=capaInput.files[0];if(!file)return;statusEl.textContent='Enviando capa para o Cloudinary…';try{await enviar(file,'capa');statusEl.textContent='Capa atualizada.';setTimeout(()=>location.reload(),500)}catch(e){statusEl.textContent='Erro: '+e.message;alert(e.message)}});
async function excluirFoto(button,publicId){if(!publicId)return;if(!confirm('Excluir esta foto? Ela será removida da galeria e do Cloudinary.'))return;button.disabled=true;button.textContent='Excluindo…';const fd=new FormData();fd.append('id',id);fd.append('csrf',csrf);fd.append('public_id',publicId);try{const r=await fetch('delete_foto.php',{method:'POST',body:fd,credentials:'same-origin'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Não foi possível excluir a foto.');const card=button.closest('.foto-editavel');card?.remove();statusEl.textContent='Foto excluída. '+j.total+' fotos restantes.';}catch(e){button.disabled=false;button.textContent='Excluir';alert(e.message);}}\nbibliotecaInput.addEventListener('change',async()=>{const files=[...bibliotecaInput.files];if(!files.length)return;fila.innerHTML='';files.forEach((f,i)=>{const el=document.createElement('div');el.className='fila-item';el.textContent=(i+1)+'. '+f.name+' · aguardando';fila.appendChild(el)});let done=0;for(let i=0;i<files.length;i++){const item=fila.children[i];item.textContent=(i+1)+'. '+files[i].name+' · enviando…';statusEl.textContent='Enviando '+(i+1)+' de '+files.length+'…';try{await enviar(files[i],'biblioteca',item);item.textContent=(i+1)+'. '+files[i].name+' · enviada';done++}catch(e){item.textContent=(i+1)+'. '+files[i].name+' · erro: '+e.message;item.classList.add('erro')}}statusEl.textContent=done+' de '+files.length+' fotos enviadas.';bibliotecaInput.value='';setTimeout(()=>location.reload(),800)});
</script></body></html>