<?php
require_once __DIR__.'/app.php'; require_login(); require_once __DIR__.'/ui.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); if(!$id) redirect('proprietarios.php');
$rows=supabase_request('GET','/rest/v1/proprietarios?select=*&id=eq.'.$id.'&limit=1'); $o=$rows[0]??null; if(!$o){flash('error','Proprietário não encontrado.');redirect('proprietarios.php');}
$props=supabase_request('GET','/rest/v1/imoveis?select=id,codigo,nome&proprietario_id=eq.'.$id.'&order=nome.asc');$props=is_array($props)?$props:[];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Editar proprietário · Central Imóveis</title><link rel="stylesheet" href="css/style.css"></head><body><main class="container pequeno"><a class="voltar" href="proprietarios.php">← Voltar aos proprietários</a><?php render_nav('proprietarios'); ?><header class="page-head"><div><span class="eyebrow">PROPRIETÁRIO</span><h1>Editar proprietário</h1><p class="subtitulo"><?=e($o['nome'])?></p></div></header><?php if($m=flash('error')):?><div class="alerta erro"><?=e($m)?></div><?php endif;?><form action="atualizar_proprietario.php" method="POST" class="formulario"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>">
<section class="form-card"><div class="form-card-title"><span>01</span><div><strong>Identificação</strong><small>Esses dados serão usados automaticamente nos contratos.</small></div></div><div class="grid"><label>Tipo<select name="tipo"><option value="pf" <?=$o['tipo']==='pf'?'selected':''?>>Pessoa física</option><option value="pj" <?=$o['tipo']==='pj'?'selected':''?>>Pessoa jurídica</option></select></label><label>Nome / razão social<input name="nome" required value="<?=e($o['nome'])?>"></label><label>CPF<input name="cpf" value="<?=e($o['cpf']??'')?>"></label><label>Profissão<input name="profissao" value="<?=e($o['profissao']??'')?>"></label><label>Gênero<input name="genero" value="<?=e($o['genero']??'')?>"></label><label>Estado civil<input name="estado_civil" value="<?=e($o['estado_civil']??'')?>"></label><label>RG<input name="rg" value="<?=e($o['rg']??'')?>"></label><label>CNPJ<input name="cnpj" value="<?=e($o['cnpj']??'')?>"></label><label>Representante legal<input name="representante_legal" value="<?=e($o['representante_legal']??'')?>"></label><label>RG do representante<input name="rg_representante" value="<?=e($o['rg_representante']??'')?>"></label><label>Telefone<input name="telefone" value="<?=e($o['telefone']??'')?>"></label><label>E-mail<input name="email" value="<?=e($o['email']??'')?>"></label></div></section>
<section class="form-card"><div class="form-card-title"><span>02</span><div><strong>Endereço</strong></div></div><div class="grid"><label>CEP<input name="cep" value="<?=e($o['cep']??'')?>"></label><label>Rua / logradouro<input name="endereco" value="<?=e($o['endereco']??'')?>"></label><label>Número<input name="numero" value="<?=e($o['numero']??'')?>"></label><label>Complemento<input name="complemento" value="<?=e($o['complemento']??'')?>"></label><label>Bairro<input name="bairro" value="<?=e($o['bairro']??'')?>"></label><label>Cidade<input name="cidade" value="<?=e($o['cidade']??'')?>"></label><label>UF<input name="uf" value="<?=e($o['uf']??'')?>"></label></div></section>
<section class="form-card"><div class="form-card-title"><span>03</span><div><strong>Pagamento</strong></div></div><div class="grid"><label>Banco<input name="banco_codigo" value="<?=e($o['banco_codigo']??'')?>"></label><label>Agência<input name="banco_agencia" value="<?=e($o['banco_agencia']??'')?>"></label><label>Tipo de conta<input name="tipo_conta" value="<?=e($o['tipo_conta']??'')?>"></label><label>Conta<input name="banco_conta" value="<?=e($o['banco_conta']??'')?>"></label><label>PIX<input name="pix" value="<?=e($o['pix']??'')?>"></label></div></section>
<?php if($props):?><section class="form-card"><div class="form-card-title"><span>04</span><div><strong>Imóveis vinculados</strong><small>O mesmo proprietário pode ter vários imóveis.</small></div></div><?php foreach($props as $p):?><a class="map-list-item" href="editar.php?id=<?=(int)$p['id']?>"><strong><?=e($p['codigo'])?> · <?=e($p['nome'])?></strong></a><?php endforeach;?></section><?php endif;?>
<div class="form-bottom"><a class="botao secundario" href="proprietarios.php">Cancelar</a><button class="botao" type="submit">Salvar proprietário</button></div></form><?php render_footer();?></main></body></html>