<?php
require_once __DIR__.'/app.php';require_login();require_once __DIR__.'/ui.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);if(!$id){flash('error','Imóvel inválido.');redirect('index.php');}
$rows=supabase_request('GET','/rest/v1/imoveis?select=*&id=eq.'.$id.'&limit=1');$imovel=$rows[0]??null;if(!$imovel){flash('error','Imóvel não encontrado.');redirect('index.php');}
$fotos=is_array($imovel['fotos']??null)?$imovel['fotos']:[];$capa=null;$biblioteca=[];foreach($fotos as $foto){if(($foto['tipo']??'')==='capa'&&!$capa)$capa=$foto;else $biblioteca[]=$foto;}$share=gallery_url($id);
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Editar <?=e($imovel['nome'])?> · Central Imóveis</title><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"></head><body><main class="container pequeno"><a class="voltar" href="index.php">← Voltar aos imóveis</a><?php render_nav('imoveis'); ?><header class="page-head"><div><span class="eyebrow">IMÓVEL · <?=e($imovel['codigo'])?></span><h1>Editar imóvel</h1><p class="subtitulo"><?=e($imovel['nome'])?></p></div></header>
<?php if($error=flash('error')):?><div class="alerta erro"><?=e($error)?></div><?php endif;?><?php if($success=flash('success')):?><div class="alerta sucesso"><?=e($success)?></div><?php endif;?>
<form action="atualizar.php" method="POST" class="formulario"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>">
<div class="grid"><label>Código *<input name="codigo" required maxlength="50" value="<?=e($imovel['codigo'])?>"></label><label>Nome *<input name="nome" required maxlength="150" value="<?=e($imovel['nome'])?>"></label></div><label>Proprietário<select name="proprietario_id"><option value="">Sem proprietário vinculado</option><?php $owners=supabase_request('GET','/rest/v1/proprietarios?select=id,nome,tipo&order=nome.asc'); foreach((array)$owners as $owner): ?><option value="<?= (int)$owner['id'] ?>" <?=((int)($imovel['proprietario_id']??0)===(int)$owner['id'])?'selected':''?>><?= e($owner['nome']) ?><?= ($owner['tipo']??'pf')==='pj'?' · PJ':'' ?></option><?php endforeach; ?></select></label><input type="hidden" name="proprietario" value="<?=e($imovel['proprietario']??'')?>">
<section class="address-panel"><div class="address-panel-head"><div><span class="eyebrow">LOCALIZAÇÃO</span><strong>Escolha a posição do imóvel no mapa</strong></div><small class="field-status">A posição interna pode ser exata; ela nunca será exibida dessa forma ao cliente.</small></div>
<div class="grid"><label>CEP<input id="cep" name="cep" inputmode="numeric" maxlength="9" value="<?=e($imovel['cep']??'')?>"></label><button id="cepBtn" class="botao secundario" type="button" style="align-self:end">Buscar CEP</button></div>
<div class="grid"><label>Rua / logradouro<input id="endereco" name="endereco" maxlength="250" value="<?=e($imovel['endereco']??'')?>"></label><label>Número<input id="numero" name="numero" maxlength="20" value="<?=e($imovel['numero']??'')?>"></label></div><div class="grid"><label>Bairro<input id="bairro" name="bairro" maxlength="100" value="<?=e($imovel['bairro']??'')?>>"></label><label>Cidade<input id="cidade" name="cidade" maxlength="100" value="<?=e($imovel['cidade']??'São Sebastião')?>"></label></div><div class="grid"><label>UF<input id="uf" name="uf" maxlength="2" value="<?=e($imovel['uf']??'SP')?>"></label><label>Complemento<input id="complemento" name="complemento" maxlength="120" value="<?=e($imovel['complemento']??'')?>"></label></div>
<div id="pickerMap" class="map-picker"></div><p class="map-help">Clique no mapa para colocar a casa. Você também pode arrastar a marcação. As coordenadas serão salvas somente para o Central.</p><div class="grid"><label>Latitude<input id="latitude" type="number" step="any" name="latitude" value="<?=e($imovel['latitude']??'')?>"></label><label>Longitude<input id="longitude" type="number" step="any" name="longitude" value="<?=e($imovel['longitude']??'')?>"></label></div></section>
<div class="grid quatro"><label>Capacidade<input type="number" name="capacidade" min="0" value="<?= (int)$imovel['capacidade']?>"></label><label>Dormitórios<input type="number" name="dormitorios" min="0" value="<?= (int)$imovel['dormitorios']?>"></label><label>Suítes<input type="number" name="suites" min="0" value="<?= (int)$imovel['suites']?>"></label><label>Distância da praia (m)<input type="number" name="distancia_praia" min="0" value="<?= (int)$imovel['distancia_praia']?>"></label></div>
<div class="checks"><label><input type="checkbox" name="suite_terrea" <?=!empty($imovel['suite_terrea'])?'checked':''?>> Suíte térrea</label><label><input type="checkbox" name="piscina" <?=!empty($imovel['piscina'])?'checked':''?>> Piscina</label><label><input type="checkbox" name="churrasqueira" <?=!empty($imovel['churrasqueira'])?'checked':''?>> Churrasqueira</label><label><input type="checkbox" name="ar_condicionado" <?=!empty($imovel['ar_condicionado'])?'checked':''?>> Ar-condicionado</label></div><label>Diária base<input type="number" name="diaria" min="0" step="0.01" value="<?=e($imovel['diaria'])?>"></label><label>Descrição<textarea name="descricao" rows="7"><?=e($imovel['descricao']??'')?></textarea></label><label class="check-unico"><input type="checkbox" name="ativo" <?=!empty($imovel['ativo'])?'checked':''?>> Imóvel ativo</label>
<section class="share-actions"><div><span class="eyebrow">PARA O LOCATÁRIO</span><h2>Enviar este imóvel</h2><p>Você pode mandar as fotos em PDF ou um anúncio estático. A localização pode ficar oculta ou aparecer apenas como área aproximada.</p></div><div class="acoes-form"><a class="botao secundario" target="_blank" href="<?=e($share.'&modo=pdf')?>">PDF das fotos</a><a class="botao secundario" target="_blank" href="<?=e($share.'&anuncio=1&localizacao=0')?>">Anúncio · sem localização</a><?php if(!empty($imovel['latitude'])&&!empty($imovel['longitude'])):?><a class="botao secundario" target="_blank" href="<?=e($share.'&anuncio=1&localizacao=1')?>">Anúncio · localização aproximada</a><?php endif;?></div></section>
<section class="fotos-editor"><div class="secao-titulo"><div><span class="eyebrow">FOTOS</span><h2>Foto de capa</h2><p>A capa aparece primeiro no anúncio.</p></div></div><div class="upload-row"><label class="upload-box"><span class="upload-icone">＋</span><span><strong>Escolher capa</strong><small>JPG, PNG, WEBP ou GIF</small></span><input id="capaInput" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><div class="mini-preview"><?php if($capa):?><img src="<?=e($capa['url'])?>" alt="Capa"><small>Capa atual</small><?php else:?><small>Nenhuma capa.</small><?php endif;?></div></div></section>
<section class="fotos-editor"><div class="secao-titulo"><div><span class="eyebrow">ACERVO</span><h2>Fotos</h2><p>Envio direto para o Cloudinary. Quantidade livre.</p></div></div><label class="upload-box"><span class="upload-icone">＋</span><span><strong>Adicionar fotos</strong><small>Selecione várias e o sistema envia em fila.</small></span><input id="bibliotecaInput" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><div id="uploadStatus" class="upload-status">Nenhum upload em andamento.</div><div id="fila" class="fila"></div></section>
<section class="fotos-editor"><div class="secao-titulo"><div><span class="eyebrow">GALERIA</span><h2>Fotos atuais</h2></div><div class="acoes-form"><a class="botao secundario" target="_blank" href="<?=e($share)?>">Abrir galeria</a><a class="botao secundario" href="download_fotos.php?id=<?=$id?>">Baixar ZIP</a></div></div><div class="galeria-editavel"><?php foreach($fotos as $foto):$pid=(string)($foto['public_id']??'');?><div class="foto-editavel"><div class="foto-thumb"><img src="<?=e($foto['url']??'')?>" alt="Foto"></div><div class="foto-meta"><small><?=($foto['tipo']??'biblioteca')==='capa'?'CAPA':'BIBLIOTECA'?></small><button class="excluir-foto" type="button" onclick="excluirFoto(this,<?=json_encode($pid)?>)">Excluir</button></div></div><?php endforeach;?></div></section>
<div class="acoes-form save-zone"><a class="botao secundario" href="contratos.php?imovel=<?=$id?>">Contrato deste imóvel</a><a class="botao secundario" href="index.php">Cancelar</a><button class="botao" type="submit">Salvar</button></div>
</form><?php render_footer();?></main>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const id=<?=$id?>,csrf=<?=json_encode(csrf_token())?>;let lat=Number(<?=json_encode($imovel['latitude'])?>),lng=Number(<?=json_encode($imovel['longitude'])?>);const latInput=document.getElementById('latitude'),lngInput=document.getElementById('longitude');const map=L.map('pickerMap');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const icon=L.divIcon({className:'central-house-marker',html:'<span>⌂</span>',iconSize:[34,34],iconAnchor:[17,30]});let marker=null;function setPoint(a,b){lat=a;lng=b;latInput.value=a.toFixed(7);lngInput.value=b.toFixed(7);if(marker)marker.setLatLng([a,b]);else marker=L.marker([a,b],{icon,draggable:true}).addTo(map).on('dragend',e=>{const p=e.target.getLatLng();setPoint(p.lat,p.lng)});map.setView([a,b],16)}if(Number.isFinite(lat)&&Number.isFinite(lng))setPoint(lat,lng);else map.setView([-23.76,-45.72],12);map.on('click',e=>setPoint(e.latlng.lat,e.latlng.lng));latInput.addEventListener('change',()=>{const a=parseFloat(latInput.value),b=parseFloat(lngInput.value);if(Number.isFinite(a)&&Number.isFinite(b))setPoint(a,b)});
const cep=document.getElementById('cep');document.getElementById('cepBtn').addEventListener('click',async()=>{const v=cep.value.replace(/\D/g,'');if(v.length!==8)return;const r=await fetch('https://viacep.com.br/ws/'+v+'/json/');const d=await r.json();if(d.erro)return;document.getElementById('endereco').value=d.logradouro||'';document.getElementById('bairro').value=d.bairro||'';document.getElementById('cidade').value=d.localidade||'';document.getElementById('uf').value=d.uf||'';});
async function enviar(file,tipo){const fd=new FormData();fd.append('id',id);fd.append('csrf',csrf);fd.append('tipo',tipo);fd.append('foto',file);const r=await fetch('upload_foto.php',{method:'POST',body:fd,credentials:'same-origin'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Falha no upload');return j}
const capaInput=document.getElementById('capaInput'),bibliotecaInput=document.getElementById('bibliotecaInput'),statusEl=document.getElementById('uploadStatus'),fila=document.getElementById('fila');capaInput.addEventListener('change',async()=>{if(!capaInput.files[0])return;statusEl.textContent='Enviando capa…';try{await enviar(capaInput.files[0],'capa');location.reload()}catch(e){statusEl.textContent=e.message}});bibliotecaInput.addEventListener('change',async()=>{const files=[...bibliotecaInput.files];if(!files.length)return;fila.innerHTML='';for(let i=0;i<files.length;i++){const el=document.createElement('div');el.className='fila-item';el.textContent=(i+1)+' de '+files.length+' · '+files[i].name+' · enviando';fila.appendChild(el);try{await enviar(files[i],'biblioteca');el.textContent=(i+1)+' de '+files.length+' · '+files[i].name+' · enviada';el.classList.add('ok')}catch(e){el.textContent=(i+1)+' de '+files.length+' · '+files[i].name+' · '+e.message;el.classList.add('erro')}}statusEl.textContent='Fila concluída.';bibliotecaInput.value='';setTimeout(()=>location.reload(),700)});
async function excluirFoto(button,pid){if(!pid||!confirm('Excluir esta foto? Ela também será removida do Cloudinary.'))return;button.disabled=true;const fd=new FormData();fd.append('id',id);fd.append('csrf',csrf);fd.append('public_id',pid);const r=await fetch('delete_foto.php',{method:'POST',body:fd});const j=await r.json();if(!r.ok||!j.ok){alert(j.error||'Não foi possível excluir.');button.disabled=false;return}button.closest('.foto-editavel').remove()}
</script><style>.map-picker{height:390px;border:1px solid #d9dee3;border-radius:14px;overflow:hidden;margin-top:12px}.map-help{color:#6d7782;font-size:12px;line-height:1.5}.share-actions{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:20px;border:1px solid var(--line);border-radius:16px;background:var(--surface-2)}.share-actions h2{margin:4px 0}.share-actions p{margin:0;color:var(--muted);font-size:13px;max-width:650px}.save-zone{justify-content:flex-end;margin-top:10px;padding-top:20px;border-top:1px solid var(--line)}.address-panel{padding:18px;border:1px solid var(--line);border-radius:16px;background:var(--surface-2)}.address-panel-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.address-panel-head strong{display:block;margin-top:4px}.field-status{color:var(--muted);font-size:11px;max-width:360px}.central-house-marker{background:transparent;border:0}.central-house-marker span{display:grid;place-items:center;width:34px;height:34px;border-radius:50% 50% 50% 6px;transform:rotate(-45deg);background:#fff;border:2px solid #d71920;box-shadow:0 3px 12px rgba(0,0,0,.18);font-size:20px;font-weight:900;color:#17212b}.central-house-marker span:after{content:''}.foto-thumb img{display:block;width:100%;height:120px;object-fit:cover}@media(max-width:650px){.address-panel-head,.share-actions{display:block}.share-actions .acoes-form{margin-top:14px}.share-actions .botao{width:100%}.save-zone .botao{flex:1}.map-picker{height:320px}}</style></body></html>