<?php
/* Shared Central UI: restrained, property-product style, not a generic SaaS dashboard. */
?>
<style>
:root{--ui-bg:#f7f7f5;--ui-surface:#fff;--ui-text:#17212b;--ui-muted:#6d7782;--ui-line:#dedfdc;--ui-accent:#c91824;--ui-shadow:0 10px 28px rgba(20,25,30,.07)}
html[data-theme="dark"]{--ui-bg:#111315;--ui-surface:#191c1f;--ui-text:#f2f3f4;--ui-muted:#a4abb3;--ui-line:#30353a;--ui-shadow:0 14px 35px rgba(0,0,0,.28)}
body{background:var(--ui-bg)!important;color:var(--ui-text)!important}body:before{background:var(--ui-accent)!important}.main-nav{display:none!important}
.central-menu-button{position:fixed;top:17px;right:18px;z-index:1200;width:40px;height:36px;border:1px solid var(--ui-line);border-radius:9px;background:var(--ui-surface);color:var(--ui-text);cursor:pointer;font-size:19px;line-height:1;box-shadow:var(--ui-shadow)}
.central-drawer{position:fixed;inset:0;z-index:1190;pointer-events:none}.central-drawer-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.35);opacity:0;transition:.2s}.central-drawer-panel{position:absolute;top:0;right:0;height:100%;width:min(300px,86vw);background:var(--ui-surface);border-left:1px solid var(--ui-line);padding:76px 18px 22px;transform:translateX(100%);transition:.23s;box-shadow:-20px 0 50px rgba(0,0,0,.12)}.central-drawer.open{pointer-events:auto}.central-drawer.open .central-drawer-backdrop{opacity:1}.central-drawer.open .central-drawer-panel{transform:none}.central-drawer-title{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--ui-muted);margin:0 0 12px}.central-drawer a,.central-logout,.central-theme{display:flex;align-items:center;justify-content:space-between;width:100%;padding:11px 10px;border:0;border-radius:8px;background:transparent;color:var(--ui-text);font-size:14px;text-align:left;text-decoration:none;cursor:pointer}.central-drawer a:hover,.central-logout:hover,.central-theme:hover{background:rgba(120,130,140,.09)}.central-drawer a.active{font-weight:800;background:rgba(120,130,140,.12)}.central-logout{margin-top:18px;border-top:1px solid var(--ui-line);border-radius:0!important;color:var(--ui-accent)!important;padding-top:18px}.central-theme{margin-top:0;border-top:1px solid var(--ui-line);border-radius:0;padding-top:18px}.central-theme small{color:var(--ui-muted)}
body.central-has-ui .painel,body.central-has-ui .card,body.central-has-ui .vazio,body.central-has-ui .fotos-editor,body.central-has-ui .profile-card,body.central-has-ui .login-box{background:var(--ui-surface)!important;border-color:var(--ui-line)!important;color:var(--ui-text)}body.central-has-ui input,body.central-has-ui select,body.central-has-ui textarea{background:var(--ui-surface);color:var(--ui-text);border-color:var(--ui-line)}body.central-has-ui .botao.secundario{background:var(--ui-surface);color:var(--ui-text);border-color:var(--ui-line)}body.central-has-ui .subtitulo,body.central-has-ui .topo p,body.central-has-ui .card p,body.central-has-ui .cabecalho-lista p{color:var(--ui-muted)}
@media(min-width:900px){.central-menu-button{top:20px;right:24px}}

/* acabamento Central — menos SaaS, mais produto imobiliário */
:root{--ui-radius:4px}
body.central-has-ui{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:-.005em}
body.central-has-ui:before{height:2px;background:var(--ui-accent)!important}
body.central-has-ui .painel,body.central-has-ui .card,body.central-has-ui .vazio,body.central-has-ui .fotos-editor,body.central-has-ui .profile-card,body.central-has-ui .form-card{border-radius:2px!important;box-shadow:none!important}
body.central-has-ui .card{border-left:0;border-right:0}
body.central-has-ui .botao{border-radius:4px;box-shadow:none!important;transform:none!important;min-height:38px}
body.central-has-ui .botao:hover{transform:none;box-shadow:none!important}
body.central-has-ui .resumo span{border-radius:3px;background:transparent}
body.central-has-ui .main-nav{border-radius:0;box-shadow:none}
body.central-has-ui .map-list-item{border-radius:2px;box-shadow:none}
body.central-has-ui .form-card:before{width:2px}
body.central-has-ui .central-menu-button{border-radius:4px;box-shadow:none}
body.central-has-ui .central-drawer-panel{box-shadow:-12px 0 28px rgba(0,0,0,.08)}
html[data-theme="dark"] body.central-has-ui .form-card,
html[data-theme="dark"] body.central-has-ui .painel,
html[data-theme="dark"] body.central-has-ui .card{background:transparent!important}
html[data-theme="dark"] body.central-has-ui input,html[data-theme="dark"] body.central-has-ui select,html[data-theme="dark"] body.central-has-ui textarea{background:transparent}
.central-logout{font-size:13px!important;padding:9px 10px!important;margin-top:22px!important}.central-drawer-panel .central-logout{border-top:1px solid var(--ui-line);padding-top:13px!important}.profile-account{margin-top:24px}.profile-account .botao{min-height:34px!important;padding:0 11px!important;font-size:12px!important}
.site-footer .footer-profile{cursor:pointer}.site-footer .footer-profile-link{display:flex;align-items:center;gap:10px;color:inherit;text-decoration:none}
</style>
<script>
(function(){const saved=localStorage.getItem('central-theme');const prefers=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=saved||(prefers?'dark':'light');document.addEventListener('DOMContentLoaded',function(){document.body.classList.add('central-has-ui');const nav=document.querySelector('.main-nav');const items=[['Imóveis','index.php','imoveis'],['Mapa','mapa.php','mapa'],['Proprietários','proprietarios.php','proprietarios'],['Contratos','contratos.php','contratos'],['Perfil','perfil.php','perfil']];const current=(location.pathname.split('/').pop()||'index.php').split('?')[0];const button=document.createElement('button');button.className='central-menu-button';button.type='button';button.setAttribute('aria-label','Abrir menu');button.textContent='☰';document.body.appendChild(button);const drawer=document.createElement('aside');drawer.className='central-drawer';drawer.innerHTML='<div class="central-drawer-backdrop"></div><div class="central-drawer-panel"><div class="central-drawer-title">Central Imóveis</div><div class="central-links"></div><a class="central-logout" href="logout.php">Sair da conta <span>↗</span></a><button class="central-theme" type="button"><span>Tema <small id="central-theme-label"></small></span><span>◐</span></button></div>';document.body.appendChild(drawer);const links=drawer.querySelector('.central-links');if(nav){nav.querySelectorAll('a').forEach(a=>links.appendChild(a.cloneNode(true)))}else{items.forEach(([label,href,key])=>{const a=document.createElement('a');a.href=href;a.textContent=label;if(current===href)a.classList.add('active');links.appendChild(a)})}function close(){drawer.classList.remove('open');button.textContent='☰'}function open(){drawer.classList.add('open');button.textContent='×'}button.addEventListener('click',()=>drawer.classList.contains('open')?close():open());drawer.querySelector('.central-drawer-backdrop').addEventListener('click',close);const themeBtn=drawer.querySelector('.central-theme'),label=drawer.querySelector('#central-theme-label');function labelTheme(){label.textContent=document.documentElement.dataset.theme==='dark'?'Escuro':'Claro'}labelTheme();themeBtn.addEventListener('click',function(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('central-theme',next);labelTheme()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})})})();
</script>
