-- Central Imóveis: proprietários reutilizáveis, vínculo imóvel/proprietário e rascunhos de contratos.
create table if not exists public.proprietarios (
  id bigint generated by default as identity primary key,
  tipo text not null default 'pf' check (tipo in ('pf','pj')),
  nome text not null,
  cpf text, profissao text, genero text, estado_civil text, rg text, cnpj text,
  representante_legal text, rg_representante text, telefone text, email text,
  cep text, endereco text, numero text, complemento text, bairro text, cidade text, uf text,
  banco_codigo text, banco_agencia text, tipo_conta text, banco_conta text, pix text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.proprietarios enable row level security;
create policy proprietarios_service_role_all on public.proprietarios for all to service_role using (true) with check (true);
alter table public.imoveis add column if not exists proprietario_id bigint;
alter table public.imoveis add constraint imoveis_proprietario_id_fkey foreign key (proprietario_id) references public.proprietarios(id) on delete set null;
create table if not exists public.contratos (
  id bigint generated by default as identity primary key,
  imovel_id bigint not null references public.imoveis(id) on delete restrict,
  proprietario_id bigint references public.proprietarios(id) on delete set null,
  locatario_nome text, locatario_cpf text, locatario_email text, locatario_telefone text,
  data_contrato date, checkin date, checkout date,
  valor_locacao numeric not null default 0, taxa_faxina numeric not null default 0,
  caucao numeric not null default 0, comissao_pct numeric not null default 10,
  dados jsonb not null default '{}'::jsonb, status text not null default 'rascunho',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.contratos enable row level security;
create policy contratos_service_role_all on public.contratos for all to service_role using (true) with check (true);
create index if not exists imoveis_proprietario_id_idx on public.imoveis(proprietario_id);
create index if not exists contratos_imovel_id_idx on public.contratos(imovel_id);
create index if not exists contratos_proprietario_id_idx on public.contratos(proprietario_id);
